### ISSUE TITLE
Idl interface Robot::loadRobotModel is limited

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-corbaserver#103]
In the current version of the package, idl interface functions
* Robot::loadRobotModel, and
* Robot::loadHumanoidRobotModel
make the asumption that the urdf and srdf files are located in directories called respectively "`urdf`" and "`srdf`" and located in the "`package://something`" directory.
This asumption is constraining and is broken by the recent introduction of package `example-robot-data`.
I propose to change the prototypes of these functions in such a way that they take as input urdf and srdf filenames. This will break the idl API. However, it is very likely that nobody uses directly this API, since it is wrapped by the python class Robot.

@stonneau, @pFernbach, due you use this API to load robots or do you use python class Robot and derived classes.

Unfortunately, IDL dos not support function overloading and therefore, the usual deprecation method is not possible to implement.

**Comment by nim65s** [comment]
For the records, here are 4 ways to get the paths for example-robot-data models:
- With CMake & pkg-config with eg. `${EXAMPLE_ROBOT_DATA_DATAROOTDIR}/example-robot-data/robots`
- With c++ `#include <example-robot-data/path.hpp>` and you'll get `EXAMPLE_ROBOT_DATA_MODEL_DIR`
- With python `from example_robot_data.path import EXAMPLE_ROBOT_DATA_MODEL_DIR`
- With python, use `from example_robot_data import getModelPath`

But to get this `package://` working here, I usually add this path to `ROS_PACKAGE_PATH`, and this is enough.

**Comment by pFernbach** [comment]
We are using python classes derived from the Robot class, it use either the `loadModel` method from hpp-corbaserver/robot.py or our own method that do additionnal stuff related to the contact generation : 
https://github.com/humanoid-path-planner/hpp-rbprm-corba/blob/master/src/rbprmbuilder.impl.cc#L123

I think we will have to do the same changes in this method than what you are going to do in hpp-corbaserver.
