### ISSUE TITLE
hppcorbaserver crashes at initialization

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-corbaserver#107]
After calling this line https://github.com/humanoid-path-planner/hpp-corbaserver/blob/34fbb5acaa2d1767cf1bc1f77f72fe4fddc34afe/src/server.cc#L127
member impl_ may not be initialized and the following line crashes.

**Comment by jmirabel** [comment]
This works fine for me and used to work for you. If *nameService_* is true, impl_ should be initialized by *initRootPOA* otherwise, it is initialized by *initOmniINSPOA*.

What is the value of *nameService_* for you ?

**Comment by florent-lamiraux** [comment]
`nameService_` is false, and `initOmniINSPOA` returns false without allocating `impl_`.
It seems to be due to the fact that another `hppcorbaserver` is running.
