### ISSUE TITLE
Compilation error with gcc  5.4.0

### ISSUE THREAD

**Issue by pFernbach** [humanoid-path-planner/hpp-corbaserver#137]
On the master branch (for all hpp packages) I got the following compilation error on ubuntu 16.04 with gcc 5.4 :
```
[ 40%] Building CXX object src/CMakeFiles/hpp-corbaserver.dir/hpp/core_idl/distances.cc.o
cd /local/dev_hpp/src/hpp-corbaserver/build-rel/src && /usr/bin/c++   -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DPINOCCHIO_WITH_HPP_FCL -DPINOCCHIO_WITH_URDFDOM -Dhpp_corbaserver_EXPORTS -I/local/dev_hpp/src/hpp-corbaserver/build-rel -I/local/dev_hpp/src/hpp-corbaserver/build-rel/include -I/local/dev_hpp/src/hpp-corbaserver/include -I/local/dev_hpp/src/hpp-corbaserver/build-rel/src -isystem /opt/openrobots/include -isystem /local/dev_hpp/install/include -isystem /usr/include/eigen3 -isystem /usr/include/assimp  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG -fPIC   -D__x86_64__ -D__linux__ -D__OSVERSION__=2 -DHPP_FCL_HAVE_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=1 -DOCTOMAP_MINOR_VERSION=9 -DOCTOMAP_PATCH_VERSION=0 -std=gnu++11 -o CMakeFiles/hpp-corbaserver.dir/hpp/core_idl/distances.cc.o -c /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.cc
/local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.cc:11:64: error: specialization of ‘template<class ServantBaseType> std::vector<hpp::corbaServer::ServantFactoryBase<ServantBaseType>*>& hpp::corbaServer::objectDowncasts()’ in different namespace [-fpermissive]
 ::hpp::corbaServer::objectDowncasts<hpp::core_impl::Distance> ()
                                                                ^
In file included from /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances-fwd.hh:9:0,
                 from /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.hh:8,
                 from /local/dev_hpp/src/hpp-corbaserver/build-rel/src/hpp/core_idl/distances.cc:5:
/local/dev_hpp/src/hpp-corbaserver/include/hpp/corbaserver/servant-base.hh:348:58: error:   from definition of ‘template<class ServantBaseType> std::vector<hpp::corbaServer::ServantFactoryBase<ServantBaseType>*>& hpp::corbaServer::objectDowncasts()’ [-fpermissive]
     std::vector< ServantFactoryBase<ServantBaseType>* >& objectDowncasts ();
                                                          ^
src/CMakeFiles/hpp-corbaserver.dir/build.make:873 : la recette pour la cible « src/CMakeFiles/hpp-corbaserver.dir/hpp/core_idl/distances.cc.o » a échouée
```

After quick search it looks like a bug in gcc <= 7.0 that do not correctly implement the c++11 standard. Compilation with Clang (3.8) work correctly. 
It seems that some fix exist to avoid this (https://stackoverflow.com/questions/25594644/warning-specialization-of-template-in-different-namespace) but I did not try them.

**Comment by jmirabel** [comment]
This is very likely easy to fix. I'll have a look when I get some time. Is it blocking you ?

**Comment by pFernbach** [comment]
No it's not blocking. As I said, I compiled it with clang.

**Comment by jmirabel** [comment]
@nim65s Can you provide a link to a docker that reproduce this ?

**Comment by nim65s** [comment]
From the LAAS network, you can directly use `memmos.laas.fr:5000/humanoid-path-planner/hpp-corbaserver/py-hpp-corbaserver-py3:16.04` from the CI.
If you are outside, I pushed the same image to `gepetto/buildfarm:hpp-corbaserver-16.04`

This image contains all hpp-corbaserver dependencies, so you can directly clone it and build it.

**Comment by jmirabel** [comment]
In this docker, I get the following CMake error:
> -- currently used  C++ standard: 199711
CMake Error at cmake/cxx-standard.cmake:74 (message):
  CMAKE_CXX_STANDARD upgrade to >= 11 required
Call Stack (most recent call first):
  /opt/openrobots/lib/cmake/hpp-pinocchio/hpp-pinocchioConfig.cmake:180 (CHECK_MINIMAL_CXX_STANDARD)
  /opt/openrobots/lib/cmake/hpp-core/hpp-coreConfig.cmake:136 (find_package)
  cmake/package-config.cmake:84 (find_package)
  CMakeLists.txt:43 (ADD_PROJECT_DEPENDENCY)

Does it ring a bell ?

**Comment by jmirabel** [comment]
9c4ddc3

**Comment by nim65s** [comment]
It does ring a bell: this is my implementation of the behavior you asked for in https://github.com/jrl-umi3218/jrl-cmakemodules/pull/411#issuecomment-648832118
Is there any issue with it ?

Thanks for the fix, I'll test it :D

**Comment by jmirabel** [comment]
> It does ring a bell: this is my implementation of the behavior you asked for in [jrl-umi3218/jrl-cmakemodules#411 (comment)](https://github.com/jrl-umi3218/jrl-cmakemodules/pull/411#issuecomment-648832118)
> Is there any issue with it ?

This is different. Here, the CMakeLists does not ask for a specific C++ version so it should be fine to set the version to whatever required minimum.

Anyway, I think we can add
```cmake
set_minimum_cxx_standard(11 ENFORCE)
```

**Comment by nim65s** [comment]
We could implement that, but it would work only in the case where someone doesn't ask for a specific C++ version *after* the dependency declaration, and before any library / executable target declaration. I would find this fragile.

We could add a `set_minimum_cxx_standard(11 ENFORCE)`, but we would have to do that in each and every package :/

**Comment by jmirabel** [comment]
I let you decide what's best. I won't have time to handle this.
