### ISSUE TITLE
omniidl creates a hpp/corbaserver directory inside the hpp/corbaserver directory

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-corbaserver#56]
Tests are not passing, because an `import hpp.corbaserver` in the first directory will import the content of the second, as in python 2, `import` will try first to look for a relative package.
The workaround is to run `rm -rf src/hpp/corbaserver/hpp` between a `make` and a `make test`

**Comment by jmirabel** [comment]
Should be fixed by #73
