### ISSUE TITLE
Python 3: Using OmniORB 4.2.3 from robotpkg

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-corbaserver#90]
In order to build HPP with Python 3 support, one must use OmniORB 4.2.3 with Python 3 support. On ubuntu 16.04, it is available via robotpkg-py35-omniorbpy.

When launching `hppcorbaserver`, I get the following error.
```
CORBA: CORBA::Exception NO_RESOURCES:IDL:omg.org/CORBA/NO_RESOURCES:1.0 : failed to get the name service
```
This is due to OmniORB unable to find the correct configuration file. A workaround is to use:
```
hppcorbaserver -ORBconfigFile /etc/omniORB.cfg
```

**Comment by nim65s** [comment]
Another option is `export ORBInitRef=NameService=corbaname::localhost`

**Comment by jmirabel** [comment]
It seems OmniORB from robotpkg is not reading '/etc/omniORB.cfg'. Do you know which file it is reading ? '/opt/openrobots/etc/omniORB.cfg' ?

If yes, a more elegant solution is to provide such a file.

**Comment by nim65s** [comment]
Exactly: https://github.com/nim65s/robotpkg/blob/master/middleware/omniORB/Makefile#L26

I will propose this solution for robotpkg.

**Comment by nim65s** [comment]
Looking again at this, this file is already given as a sample, so:
`sudo cp /opt/openrobots/share/examples/omniORB/sample.cfg /opt/openrobots/etc/omniORB.cfg`

**Comment by jmirabel** [comment]
> Looking again at this, this file is already given as a sample, so:
> `sudo cp /opt/openrobots/share/examples/omniORB/sample.cfg /opt/openrobots/etc/omniORB.cfg`

That's a good temporary workaround. Can you make robotpkg do that automatically ?

**Comment by nim65s** [comment]
I can ask: https://git.openrobots.org/issues/215

**Comment by nim65s** [comment]
This should be fixed: https://git.openrobots.org/projects/robotpkg/repository/robotpkg/revisions/30c6b31d0099dd2f94df2393ae531f5c5d07aca9/diff

**Comment by jmirabel** [comment]
Excellent ! Thanks.
Deployment of Python 3 version is now ready, isn't it ?

**Comment by nim65s** [comment]
yes, we'll discuss that in the HPP meeting I guess :)

**Comment by jmirabel** [comment]
@nim65s this can be closed, can't it ?

**Comment by nim65s** [comment]
yep :)
